config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  get 'tags/show'
  resources :gardens do
    resources :plants, only: :create
  end
  resources :plants, only: %i[show destroy] do
    resources :plant_tags, only: :create
  end
  resources :tags, only: :show
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/garden.rb
# frozen_string_literal: true

class Garden < ApplicationRecord
  validates :name, presence: true, uniqueness: true
  validates :banner_url, presence: true

  has_many :plants, dependent: :destroy
end

app/models/plant.rb
# frozen_string_literal: true

class Plant < ApplicationRecord
  belongs_to :garden # adds a presence validation on the garden_id foreign key
  has_many :plant_tags
  has_many :tags, through: :plant_tags

  validates :name, presence: true
end

app/models/plant_tag.rb
# frozen_string_literal: true

class PlantTag < ApplicationRecord
  belongs_to :tag
  belongs_to :plant
end

app/models/tag.rb
# frozen_string_literal: true

class Tag < ApplicationRecord
  has_many :plant_tags
  has_many :plants, through: :plant_tags
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
end

app/controllers/gardens_controller.rb
# frozen_string_literal: true

class GardensController < ApplicationController
  before_action :set_garden, only: %i[show edit update destroy]

  # GET /gardens
  def index
    @gardens = Garden.all
  end

  # GET /gardens/1
  def show
    @plant = Plant.new
  end

  # GET /gardens/new
  def new
    @garden = Garden.new
  end

  # GET /gardens/1/edit
  def edit; end

  # POST /gardens
  def create
    @garden = Garden.new(garden_params)

    if @garden.save
      redirect_to @garden, notice: 'Garden was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /gardens/1
  def update
    if @garden.update(garden_params)
      redirect_to @garden, notice: 'Garden was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /gardens/1
  def destroy
    @garden.destroy
    redirect_to gardens_url, notice: 'Garden was successfully destroyed.'
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_garden
    @garden = Garden.find(params[:id])
  end

  # Only allow a trusted parameter "white list" through.
  def garden_params
    params.require(:garden).permit(:name, :banner_url)
  end
end

app/controllers/plant_tags_controller.rb
# frozen_string_literal: true

class PlantTagsController < ApplicationController
  def create
    @plant_tag = PlantTag.new
    @plant_tag.tag = Tag.find(params[:plant_tag][:tag])
    @plant_tag.plant = Plant.find(params[:plant_id])
    @plant = @plant_tag.plant
    if @plant_tag.save
      redirect_to garden_path(@plant.garden)
    else
      render 'plants/show'
    end
  end
end

app/controllers/plants_controller.rb
# frozen_string_literal: true

class PlantsController < ApplicationController
  def show
    @plant = Plant.find(params[:id])
    @plant_tag = PlantTag.new
  end

  def create
    @garden = Garden.find(params[:garden_id])
    @plant = Plant.new(plant_params)
    @plant.garden = @garden
    if @plant.save
      redirect_to garden_path(@garden)
    else
      render 'gardens/show'
    end
  end

  def destroy
    @plant = Plant.find(params[:id])
    garden = @plant.garden
    @plant.destroy
    redirect_to garden_path(garden)
  end

  private

  def plant_params
    params.require(:plant).permit(:name, :image_url)
  end
end

app/controllers/tags_controller.rb
# frozen_string_literal: true

class TagsController < ApplicationController
  def show
    @tag = Tag.find(params[:id])
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

app/helpers/gardens_helper.rb
# frozen_string_literal: true

module GardensHelper
end

app/helpers/plants_helper.rb
# frozen_string_literal: true

module PlantsHelper
end

app/helpers/tags_helper.rb
# frozen_string_literal: true

module TagsHelper
end

app/views/gardens/_form.html.erb
<%= simple_form_for(@garden) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <%= f.input :name %>
    <%= f.input :banner_url %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/gardens/edit.html.erb
<h1>Editing Garden</h1>

<%= render 'form', garden: @garden %>

<%= link_to 'Show', @garden %> |
<%= link_to 'Back', gardens_path %>

app/views/gardens/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Gardens</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Banner url</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @gardens.each do |garden| %>
      <tr>
        <td><%= garden.name %></td>
        <td><%= garden.banner_url %></td>
        <td><%= link_to 'Show', garden %></td>
        <td><%= link_to 'Edit', edit_garden_path(garden) %></td>
        <td><%= link_to 'Destroy', garden, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Garden', new_garden_path %>

app/views/gardens/new.html.erb
<h1>New Garden</h1>

<%= render 'form', garden: @garden %>

<%= link_to 'Back', gardens_path %>

app/views/gardens/show.html.erb
<div class="banner" style="background-image: linear-gradient(-225deg, rgba(0,101,168,0.6) 0%, rgba(0,36,61,0.6) 50%), url('<%= @garden.banner_url %>')">
  <h1><%= @garden.name %></h1>
</div>

<div class="container">
  <div class="row">
    <% @garden.plants.each do |plant| %>
      <%= render 'components/card', plant: plant %>
    <% end %>
  </div>
</div>

<div class="container">
  <div class="row">
    <div class="col-sm-4 col-sm-offset-4">
      <h4>Add a plant:</h4>
      <%= simple_form_for [ @garden, @plant ] do |f| %>
        <%= f.input :name, placeholder: "Palm tree" %>
        <%= f.input :image_url, placeholder: "https://raw.githubusercontent.com/lewagon/fullstack-images/master/rails/parks-and-plants/philo.jpg" %>
        <%= f.submit "Add", class: "btn btn-primary" %>
      <% end %>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Plants</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/plants/show.html.erb
<h1><%= @plant.name %></h1>


<%= simple_form_for [ @plant, @plant_tag ] do |f| %>
  <%= f.input :tag, collection: Tag.all %>
  <%= f.submit "Add tag", class: 'btn btn-primary' %>
<% end %>

app/views/tags/show.html.erb
<h1><%= @tag.name %></h1>


<% @tag.plants.each do |plant| %>
  <%= render 'components/card', plant: plant %>
<% end %>